"""fix admin in user role enum

Revision ID: 001032a769df
Revises: dd14f7ca85db
Create Date: 2026-05-29 00:19:19.023389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001032a769df'
down_revision: Union[str, Sequence[str], None] = 'dd14f7ca85db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'SHOP_OWNER', 'STAFF', 'CUSTOMER', name='user_role_enum', create_constraint=True), nullable=False))
    op.execute("ALTER TYPE user_role_enum ADD VALUE 'ADMIN'")
    op.drop_index(op.f('ix_users_user_role'), table_name='users')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role', postgresql.ENUM('SHOP_OWNER', 'STAFF', 'CUSTOMER', name='user_role_enum'), autoincrement=False, nullable=False))
    op.drop_index('ix_users_role', table_name='users')
    op.create_index(op.f('ix_users_user_role'), 'users', ['user_role'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
