"""add sides_per_page column and fix some issue

Revision ID: 07abe04b8a03
Revises: 6b01bc339f9b
Create Date: 2026-05-18 07:17:24.381602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07abe04b8a03'
down_revision: Union[str, Sequence[str], None] = '6b01bc339f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('printing_price', sa.Numeric(precision=8, scale=4), nullable=False))
    op.add_column('order_items', sa.Column('sides_per_page', sa.Integer(), nullable=False))
    op.drop_column('order_items', 'price_per_page')
    op.drop_constraint(op.f('orders_created_by_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_created_by_fkey'), 'orders', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.add_column('order_items', sa.Column('price_per_page', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'sides_per_page')
    op.drop_column('order_items', 'printing_price')
    # ### end Alembic commands ###
