"""add activation_codes

Revision ID: 162592038e8a
Revises: cb61810312fd
Create Date: 2026-05-13 12:48:11.048108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162592038e8a'
down_revision: Union[str, Sequence[str], None] = 'cb61810312fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_activation_codes_code', 'activation_codes', ['code'], unique=False)
    op.create_index('ix_activation_codes_is_active', 'activation_codes', ['is_active'], unique=False)
    op.create_index('ix_activation_codes_plan_id', 'activation_codes', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activation_codes_plan_id', table_name='activation_codes')
    op.drop_index('ix_activation_codes_is_active', table_name='activation_codes')
    op.drop_index('ix_activation_codes_code', table_name='activation_codes')
    op.drop_table('activation_codes')
    # ### end Alembic commands ###
