"""edit book table and add useful columns

Revision ID: 2211b82eb9de
Revises: 162592038e8a
Create Date: 2026-05-15 11:35:31.929573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2211b82eb9de'
down_revision: Union[str, Sequence[str], None] = '162592038e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('books', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('local_file_path', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('books', 'is_saved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_saved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'local_file_path')
    op.drop_column('books', 'file_size')
    op.drop_column('books', 'created_by')
    # ### end Alembic commands ###
