"""add idx_expenses_tenant_date to expenses table

Revision ID: 24195e9b62b0
Revises: 906f5c52ee51
Create Date: 2026-06-01 11:04:07.281472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24195e9b62b0'
down_revision: Union[str, Sequence[str], None] = '906f5c52ee51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_expenses_tenant_date', 'expenses', ['tenant_id', 'expense_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expenses_tenant_date', table_name='expenses')
    # ### end Alembic commands ###
