"""remvove customer_id col and i will get it from order

Revision ID: 48816dd0d313
Revises: 07abe04b8a03
Create Date: 2026-05-19 10:49:27.548628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48816dd0d313'
down_revision: Union[str, Sequence[str], None] = '07abe04b8a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_constraint(op.f('payments_customer_id_fkey'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payments_customer_id_fkey'), 'payments', 'users', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    # ### end Alembic commands ###
