"""add description column in pricing rules

Revision ID: 6b01bc339f9b
Revises: ab6a23931add
Create Date: 2026-05-17 14:26:49.421146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b01bc339f9b'
down_revision: Union[str, Sequence[str], None] = 'ab6a23931add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_pricing_rule'), 'pricing_rules', type_='unique')
    op.create_unique_constraint('uq_pricing_rule', 'pricing_rules', ['tenant_id', 'component_type', 'component_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pricing_rule', 'pricing_rules', type_='unique')
    op.create_unique_constraint(op.f('uq_pricing_rule'), 'pricing_rules', ['component_type', 'component_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('pricing_rules', 'description')
    # ### end Alembic commands ###
