"""add completed_at col to order table

Revision ID: 906f5c52ee51
Revises: 61a38d0473c7
Create Date: 2026-06-01 10:31:57.796590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906f5c52ee51'
down_revision: Union[str, Sequence[str], None] = '61a38d0473c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'completed_at')
    # ### end Alembic commands ###
