"""rename col from type to notification_type to ensure it not make error with bulit-in python keyword

Revision ID: 9bf8f282323e
Revises: a6b3adbe51bf
Create Date: 2026-05-30 08:36:21.883820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bf8f282323e'
down_revision: Union[str, Sequence[str], None] = 'a6b3adbe51bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_type', sa.Enum('ORDER', 'PAYMENT', 'SYSTEM', 'ALERT', name='notification_type_enum', create_constraint=True), nullable=False))
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', postgresql.ENUM('ORDER', 'PAYMENT', 'SYSTEM', 'ALERT', name='notification_type_enum'), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'notification_type')
    # ### end Alembic commands ###
