"""fix enums to ensure is in db

Revision ID: a6b3adbe51bf
Revises: 001032a769df
Create Date: 2026-05-29 01:03:59.578763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b3adbe51bf'
down_revision: Union[str, Sequence[str], None] = '001032a769df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE payment_method_enum ADD VALUE 'BALANCE';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE payment_method_enum DROP VALUE 'BALANCE';")
    # ### end Alembic commands ###
