"""edit type name in material transactions

Revision ID: ab6a23931add
Revises: 2211b82eb9de
Create Date: 2026-05-16 19:24:06.552037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab6a23931add'
down_revision: Union[str, Sequence[str], None] = '2211b82eb9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_transactions', sa.Column('transaction_type', sa.Enum('RESTOCK', 'CONSUMPTION', 'ADJUSTMENT', 'RETURN', name='material_transaction_type_enum', create_constraint=True), nullable=False))
    op.drop_index(op.f('ix_material_transactions_type'), table_name='material_transactions')
    op.create_index('ix_material_transactions_transaction_type', 'material_transactions', ['transaction_type'], unique=False)
    op.drop_constraint(op.f('material_transactions_material_id_fkey'), 'material_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'material_transactions', 'materials', ['material_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('material_transactions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_transactions', sa.Column('type', postgresql.ENUM('RESTOCK', 'CONSUMPTION', 'ADJUSTMENT', 'RETURN', name='material_transaction_type_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'material_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('material_transactions_material_id_fkey'), 'material_transactions', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_material_transactions_transaction_type', table_name='material_transactions')
    op.create_index(op.f('ix_material_transactions_type'), 'material_transactions', ['type'], unique=False)
    op.drop_column('material_transactions', 'transaction_type')
    # ### end Alembic commands ###
