"""add balance col in tenant member and balance enum

Revision ID: c91cd909e2d1
Revises: 48816dd0d313
Create Date: 2026-05-19 11:38:43.029009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c91cd909e2d1'
down_revision: Union[str, Sequence[str], None] = '48816dd0d313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'MOBILE_WALLET', 'BALANCE', 'OTHER', name='payment_method_enum', create_constraint=True), nullable=False))
    op.drop_column('payments', 'method')
    op.add_column('tenant_members', sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_members', 'balance')
    op.add_column('payments', sa.Column('method', postgresql.ENUM('CASH', 'BANK_TRANSFER', 'MOBILE_WALLET', 'OTHER', name='payment_method_enum'), autoincrement=False, nullable=False))
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
