"""add useful index to order table

Revision ID: c9723f955a4c
Revises: 24195e9b62b0
Create Date: 2026-06-01 11:13:07.065067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9723f955a4c'
down_revision: Union[str, Sequence[str], None] = '24195e9b62b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_orders_tenant_status', 'orders', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_orders_tenant_status_completed', 'orders', ['tenant_id', 'status', 'completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_tenant_status_completed', table_name='orders')
    op.drop_index('idx_orders_tenant_status', table_name='orders')
    # ### end Alembic commands ###
