"""add admin in user role enum

Revision ID: dd14f7ca85db
Revises: e89fc58ca7c9
Create Date: 2026-05-28 19:27:10.482165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd14f7ca85db'
down_revision: Union[str, Sequence[str], None] = 'e89fc58ca7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role', sa.Enum('ADMIN', 'SHOP_OWNER', 'STAFF', 'CUSTOMER', name='user_role_enum', create_constraint=True), nullable=False))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_index('ix_users_user_role', 'users', ['user_role'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('SHOP_OWNER', 'STAFF', 'CUSTOMER', name='user_role_enum'), autoincrement=False, nullable=False))
    op.drop_index('ix_users_user_role', table_name='users')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
