"""edit activation_codes table

Revision ID: e89fc58ca7c9
Revises: ec8458a40185
Create Date: 2026-05-28 19:20:05.823422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89fc58ca7c9'
down_revision: Union[str, Sequence[str], None] = 'ec8458a40185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activation_codes_code'), table_name='activation_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activation_codes_code'), 'activation_codes', ['code'], unique=False)
    # ### end Alembic commands ###
