"""Add cols to payment

Revision ID: ec8458a40185
Revises: c91cd909e2d1
Create Date: 2026-05-19 22:28:25.360597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8458a40185'
down_revision: Union[str, Sequence[str], None] = 'c91cd909e2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('add_to_balance', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('payments', sa.Column('split_cash_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payments', sa.Column('excess_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'excess_amount')
    op.drop_column('payments', 'split_cash_amount')
    op.drop_column('payments', 'add_to_balance')
    # ### end Alembic commands ###
